### ISSUE TITLE
Planned feature: recording migration events

### ISSUE THREAD

**Issue by jeromekelleher** [jeromekelleher/msprime#10]
It is useful to know where a given lineage was a particular time, for example to allow us to paint haplotypes with the origins of mutations. There are two phases to this:
1. Update coalescence records to record the ID of the deme in which the coalescence occured. This is a straightforward change.
2. Create a new `migration_record` object that records the lineage and source and destination for every migration event that occurs. This has the potential to be quite large, so migration records should probably not be stored by default.

**Comment by jeromekelleher** [comment]
Part (1) above has been completed in version 0.3.0. Part (2) is scheduled soon.

**Comment by aylwyn** [comment]
Just adding my support for this feature request/plan - I think it would be a helpful feature for certain use cases. Part 1 (implemented) has already been useful for us.

**Comment by jeromekelleher** [comment]
Thanks for the feedback @aylwyn --- I'll push this up the priority list and try and get it in for 0.3.3.

**Comment by jeromekelleher** [comment]
Closing this; migrations are now fully supported and documented.
