### ISSUE TITLE
make an example.hdf5 available

### ISSUE THREAD

**Issue by hyanwong** [jeromekelleher/msprime#102]
e.g. as used in example.R. Perhaps put it in tests/data/?

**Comment by jeromekelleher** [comment]
Well, it's trivial to generate one and the HDF5 file format is evolving quite quickly, so I don't think there's a lot of point in storing an example in the git repo (particularly since it's a binary blob). To generate an example,  run
```bash
$ msp simulate 10 example.hdf5
```

**Comment by hyanwong** [comment]
Fine. I didn't realise the format was so fluid at the moment. I'll just put a system call to generate the file within the R script then.

**Comment by hyanwong** [comment]
p.s. where is the msp binary created. I can't see it when compiling in the github repo

**Comment by jeromekelleher** [comment]
You can use ``python msp_dev.py`` when running in the development environment. Setuptools takes care of installing the ``msp`` binary in the right place, see

https://github.com/jeromekelleher/msprime/blob/master/setup.py#L135
