### ISSUE TITLE
newick_trees() should return (bounds, tree) not (length, tree)

### ISSUE THREAD

**Issue by hyanwong** [jeromekelleher/msprime#104]
I wonder return values from each newick_trees() iterated call should be changed. Instead of (length, tree) it might be more helpful to return a nested tuple: ((left_boundary, right_boundary), tree). Length is a trivial calculation from that, but otherwise you have to dig through the ts object to get the regions over which each tree applies.

**Comment by hyanwong** [comment]
Actually, it would also be useful to return the bounds in terms of variants too, i.e. the lowest mutation index and the highest mutation index (the latter possibly non-inclusive).

**Comment by jeromekelleher** [comment]
A better pattern might be to just return the newick string from the iterator for the user to zip together the trees iter. I.e.
```python
for tree, newick_string in zip(ts.trees(), ts.newick_trees()):
     mutations = list(tree.mutations())
     print(tree.interval, mutations[0].position, mutations[1].position, newick_string)
```
Otherwise, we'll get into a rabbits hole of things that would be handy to go with the newick tree.

**Comment by hyanwong** [comment]
Yes, this would also work, and is more flexible. Then you could remove the length part returned by the function, and just return a set of tree strings, which is cleaner. I presume your method is optimised by the compiler so that it will be not much slower than incorporating return values. If that is to be the way forward, the example above would be a useful thing to include when documentation is written for newick_trees().
