### ISSUE TITLE
Document generate_mutations() method

### ISSUE THREAD

**Issue by hyanwong** [jeromekelleher/msprime#111]
I'd like to take an already-simulated genealogical structure and throw down different numbers of mutations (i.e. change the mutation rate, but leave the coalescence structure the same). I can think of 2 ways to do this, both of which require some changes to the API. One way would be to specify separate RNGs for the coalescence part of the simulation and for the mutational part, perhaps as optional params to simulate(), in which case I can run simulate(coal_rng=rng1, mut_rng=rng2), and simply seed rng1 with the same seed before each simulation. The other way would be to have a separate API call that redoes the part of the simulation that throws down mutations, in the same way that you can all set_mutations().

**Comment by hyanwong** [comment]
Ah, I see from the code that I can do it via ts.generate_mutations(mu, rng), and that you eventually intend to document this. So this can probably be closed.

**Comment by jeromekelleher** [comment]
This is a little tricky, as work is underway to make the tree sequence object immutable. As part of this, the (undocumented) set_mutations and generate_mutations methods will be removed. We can still create a new tree sequence from a given set of records and arbitrary mutations, it's just the way of doing it will change.

It would help to understand the motivation for separating the tree and mutation simulation processes; would you mind sketching this out a bit?

**Comment by hyanwong** [comment]
I want to see how ancestry inference techniques improve as the density of mutations increases. For this, it is helpful to be able to use the same tree, and throw different densities of mutations onto it, then see how the ARG inference improves. If I have to use different trees each time, it becomes an unwanted extra source of error variation.

**Comment by jeromekelleher** [comment]
I see... I'll try to incorporate this into the refactor going on in #105.

**Comment by hyanwong** [comment]
Here's an example of a plot which uses the same simulation (the lines join points that use the same simulation) but with different mutations thrown onto the trees.
[FastARG_metrics.pdf](https://github.com/jeromekelleher/msprime/files/682130/FastARG_metrics.pdf)

**Comment by hyanwong** [comment]
A slightly less optimal, but quite workable solution would be my suggestion for allowing different RNGs for the ancestry and mutation parts of an msprime simulation. Then I could re-create the simulation using the same RNG seed, but use different seeds for the mutational part.

**Comment by hyanwong** [comment]
It would be useful to know - are you thinking of implementing the 2 different RNGs (or possibly 2 different rng seeds) approach? This makes a small difference to the parameters I will need to store when running duplicate simulations.

**Comment by jeromekelleher** [comment]
Sorry @hyanwong, I haven't figured this one out yet.

**Comment by jeromekelleher** [comment]
Semi-solved in #128.
