### ISSUE TITLE
Map column in read_hapmap not fully ignored as specified in docs

### ISSUE THREAD

**Issue by jeromekelleher** [jeromekelleher/msprime#13]
The  Map(cM) column is currently required to be 0 in the first row. This is an unnecessary restriction and should be removed, since we're ignoring the column in general.

**Comment by raflopjr** [comment]
Was this ever resolved? I'm attempting to use read_hapmap() but keep failing assert rate=0

**Comment by jeromekelleher** [comment]
This should have been resolved @raflopjr --- what version of msprime are you using?

**Comment by raflopjr** [comment]
Currently running 0.4.0

**Comment by jeromekelleher** [comment]
OK, that does sound like a problem. Can you send me an example file (or a link to it) so I can sort it out? Thanks.

**Comment by raflopjr** [comment]
This is the original file and temp is the modified file to match the format in the msprime documentation
[temp.txt](https://github.com/jeromekelleher/msprime/files/1455268/temp.txt)
[genetic_map_GRCh37_chr1.txt](https://github.com/jeromekelleher/msprime/files/1455269/genetic_map_GRCh37_chr1.txt)

**Comment by jeromekelleher** [comment]
It looks like you have a slightly funny genetic map here @raflopjr, as the rates are non-zero for every row. This doesn't make sense, because we can only have n - 1 rates. By convention we require the last rate to be zero (as stated in the docs). Where did you get this map from?

I've opened a PR to give better error on this condition in #305. If you think that the input you have is a valid map and we should do something different please comment either there or open a new issue.

This is a different error to the original issue, so I'm going to reclose the issue.
