### ISSUE TITLE
Feature request: write_vcf with CHR != 1

### ISSUE THREAD

**Issue by jackkamm** [jeromekelleher/msprime#134]
It would be nice if TreeSequence.write_vcf could take in a chromosome_label parameter, so as to easily simulate datasets with multiple chromosomes, with each chromosome in a separate vcf file.

**Comment by jeromekelleher** [comment]
Great idea, thanks @jackkamm! This should be easy enough to do. Unfortunately, we're in the middle of a fairly hefty refactor at the moment, and there aren't any releases planned for a few months. Is this something you need urgently, or more of a 'nice to have'?

**Comment by jackkamm** [comment]
Just a "nice to have", I can work around it with StringIO and PyVCF.

ps thanks for your work on this project, it's really great, I should have started using it sooner!

**Comment by jeromekelleher** [comment]
> Just a "nice to have", I can work around it with StringIO and PyVCF.

OK, cool, I'll put this in before the next release

> ps thanks for your work on this project, it's really great, I should have started using it sooner!

Thanks, great to hear you're finding it useful!
