### ISSUE TITLE
Update load_txt to take nodes, edgesets, sites and mutations files

### ISSUE THREAD

**Issue by jeromekelleher** [jeromekelleher/msprime#141]
The ``load_txt`` function needs to be updated to take files for the nodes, edgesets, sites and mutations. This will be a backward incompatible change (but this seems OK, as it's unlikely anyone is actually using it).

It would be nice if we could have flexible column management, such that we read the header to find out what columns are in there and what order they are in (particularly for the nodes file).  If the header is not present, then we assume a fixed order of columns. Ideally,  we should use numpy.loadtxt to do this, as it should make parsing much more efficient.

Once this has been updated, we should probably just remove the load_str method. We can easily update the tests that depend on it using ``msprime.load_txt(StringIO(nodes), StringIO(edgesets))``.

**Comment by jeromekelleher** [comment]
The coding this has been mostly done, but the documentation is out of date.

**Comment by petrelharp** [comment]
In a fit of procrastination, and getting straight how stuff works, I've addressed this (maybe) over in #213 .

There's still something missing in what valid sites and mutations must satisfy, though.

**Comment by jeromekelleher** [comment]
Closing this as it's out of date and taken care of by wider issues.
