### ISSUE TITLE
Update low-level error checking and messages

### ISSUE THREAD

**Issue by jeromekelleher** [jeromekelleher/msprime#146]
Error messages in the low-level C code still refer to coalescence records. Update these symbolic constants with better names and update the error messages.

**Comment by ashander** [comment]
We're now using these new APIs. To help solidify my understanding of them, I'll be contributing some fixes to this and other issues in https://github.com/jeromekelleher/msprime/milestone/3

**Comment by jeromekelleher** [comment]
That's awesome, thanks very much @ashander!
