### ISSUE TITLE
add get_num_children()

### ISSUE THREAD

**Issue by hyanwong** [jeromekelleher/msprime#152]
Trivial, but now that we can have more than 2 children in each edgeset, should there be a get_num_children() function on each edge set, rather than calling `len(edgeset.children)`.

**Comment by jeromekelleher** [comment]
In my view this is redundant --- ``len(edgeset.children)`` has almost the same number of characters as ``edgeset.num_children``, and is the canonical way of getting the length of a sequence in Python. It doesn't seem very Pythonic to me, unless there is a compelling use-case. Do you have something in mind?

**Comment by hyanwong** [comment]
Seems fine to me - only because there are other get_num_X() methods. I guess some of these are redundant in the same way.
