### ISSUE TITLE
Binary mutations not 

### ISSUE THREAD

**Issue by hyanwong** [jeromekelleher/msprime#169]
When I have some ancestral states as 1 not 0, mutations are not considered binary. E.g. with the attached files, try:

```
ts = msprime.load_text(nodes=open("TSnodes.txt"), edgesets=open("TSedges.txt"), sites=open("TSsites.txt"), mutations=open("TSmuts.txt"))
for v in ts.variants(as_bytes=True):
 print(v.position, v.genotypes.decode(), sep="\t")
```

I get

`_msprime.LibraryError: Only binary mutations are supported for this operation.a`

[TSedges.txt](https://github.com/jeromekelleher/msprime/files/871821/TSedges.txt)
[TSmuts.txt](https://github.com/jeromekelleher/msprime/files/871820/TSmuts.txt)
[TSnodes.txt](https://github.com/jeromekelleher/msprime/files/871822/TSnodes.txt)
[TSsites.txt](https://github.com/jeromekelleher/msprime/files/871823/TSsites.txt)

**Comment by jeromekelleher** [comment]
Thanks, I'll sort this out. In the mean-time you can get at the sequences using the haplotypes() method (which is basically the transpose of the variants).

**Comment by jeromekelleher** [comment]
I remember now why I didn't finish this. I've not quite figured out what the interface for variants() should be in the general case (arbitrary alphabet, lots of complicated mutations and > 2 alleles), so I postponed implementing it. (For simplicity, I'm treating anything that doesn't have 0 as ancestral and 1 as derived as nonbinary.)

Do you need the variants method, or will haplotypes do the trick?

**Comment by hyanwong** [comment]
I can use haplotypes() by sorting the array and transposing it. But how to I get the positions of all the variants?

**Comment by jeromekelleher** [comment]
This is the easiest way:
 ```python
        A = np.zeros((n, m), dtype='u1')
        for j, h in enumerate(ts.haplotypes):
            A[j] = np.fromstring(h, np.uint8) - ord('0')
```

**Comment by hyanwong** [comment]
Can this now be closed?

**Comment by jeromekelleher** [comment]
No, this is still not sorted. Hopefully we'll resolve these issues using the approach outline in #301.

**Comment by jeromekelleher** [comment]
Sorted out now in #328.
