### ISSUE TITLE
Provide API for transposed haplotypes

### ISSUE THREAD

**Issue by jeromekelleher** [jeromekelleher/msprime#2]
It is often useful to obtain the haplotypes in a per-column format. We should provide an API to do this directly.

**Comment by aylwyn** [comment]
Was this implemented? Rather than output full transposed haplotypes (or as an alternative), it would be useful just to output alleles at segregating sites.

**Comment by jeromekelleher** [comment]
I did implement a way to get the columns in the haplotype matrix (where rows are samples and columns are variants). This is actually a lot more efficient that getting the matrix row-by-row, as it avoids building the full matrix in memory.

Here is an example:
```python
ts = msprime.simulate(sample_size=10, mutation_rate=1, random_seed=1)
for position, variant in ts.variants():
    print(position, "\t", variant)
```
Gives
```
0.09280081023462117      0010000000
0.313424184685573        0010000000
0.45720480917952955      0100000000
0.7783892354927957       0000001000
0.8296033646911383       0000100000
0.8946066638454795       0010011001
```
Basically, the ``variants()`` method returns a iterator over the tuples ``(position, variant)``, where ``position`` is the location of the infinite sites mutation along the sequence, and ``variant`` is a string representing the allelic state for each sample. Thus, ``variant[0]`` is the state for sample 0, etc.

Does this help for you @aylwyn? I haven't documented this method of closed the issue because I haven't convinced myself that this is the right terminology or return signature. Any thoughts here would be much appreciated!

**Comment by aylwyn** [comment]
Looks good to me - it's essentially the output I have implemented (via the full matrix of haplotypes). One minor point is that 'position' here differs from the position returned by mutations() - would probably be good to have them consistent. In fact if anything I'd be inclined to merge the two methods somehow.

**Comment by jeromekelleher** [comment]
Thanks @aylwyn, that's good to know. I don't follow how the positions are inconsistent between the two methods though:
```python
    ts = msprime.simulate(sample_size=10, mutation_rate=1, random_seed=1)
    for position, variant in ts.variants():
        print(position, "\t", variant)
    print()
    for position, node in ts.mutations():
        print(position, "\t", node)
    print()
    for (p1, variant), (p2, node) in zip(ts.variants(), ts.mutations()):
        print(p1 == p2)
```
gives
```
0.09280081023462117      0010000000
0.313424184685573        0010000000
0.45720480917952955      0100000000
0.7783892354927957       0000001000
0.8296033646911383       0000100000
0.8946066638454795       0010011001

0.09280081023462117      2
0.313424184685573        2
0.45720480917952955      1
0.7783892354927957       6
0.8296033646911383       4
0.8946066638454795       15

True
True
True
True
True
True
```
So, the positions are identical between the two and returned in the same order. Good point on combing the information though. I'm thinking of changing the return type of the ``variants`` method to be a ``namedtuple`` so we can attach as much useful information as we need to 'variant' returned as we want. The tree node is definitely one of them.

**Comment by jeromekelleher** [comment]
This has finally been documented and fully implemented @aylwyn. Unfortunately, I've had to change the API a little bit, so this is probably going to break any code you have that uses the above signature. To stay as compatible as possible, I recommend using something like

```python
for variant in ts.variants(as_bytes=True):
     print(variant.position, variant.genotypes)
```

For the best performance, it's better to use the numpy array version though. See the [tutorial](http://msprime.readthedocs.io/en/stable/tutorial.html#variants) and [API docs](http://msprime.readthedocs.io/en/stable/api.html#msprime.TreeSequence.variants) for details.

**Comment by aylwyn** [comment]
Thanks Jerome, just got round to upgrading and new API works well.
