### ISSUE TITLE
Return SVG string from tree.draw()

### ISSUE THREAD

**Issue by koelling** [jeromekelleher/msprime#204]
It would be great if `tree.draw()` provided a way of returning the SVG string instead of only writing to a file. Maybe that could be the behaviour if `path == None` for example. This would make it possible to visualise trees directly in jupyter notebook using `IPython.display.SVG()`.

Here is a workaround wrapper function until then:

```python
import tempfile, IPython.display
def display_tree(tree, *args, **kwargs):
    with tempfile.NamedTemporaryFile() as f:
        tree.draw(f.name, *args, **kwargs)
        f.flush()
        IPython.display.display(IPython.display.SVG(filename=f.name))

#usage: display_tree(tree, show_times=True)
```

**Comment by jeromekelleher** [comment]
This is a good idea @koelling, I completely agree. What we could do is return the SVG text and make the filename an optional keyword argument. This would mean that current code should continue to work, but also enable this use-case. What do you think?

**Comment by koelling** [comment]
Sounds great!

**Comment by jeromekelleher** [comment]
It's an easy fix if you would like to have a go...
