### ISSUE TITLE
Multiple mutations on same branch in tree.draw() not being displayed

### ISSUE THREAD

**Issue by koelling** [jeromekelleher/msprime#206]
It looks like tree.draw() cannot display multiple mutations on the same branch of the tree properly. Instead, only a single red square is displayed for all of them. Presumably this is because the squares are all drawn on top of each other at the exact same location?

![screen shot 2017-06-29 at 14 51 03](https://user-images.githubusercontent.com/369559/27690884-680f0914-5cda-11e7-9044-83f9d5bad834.png)

**Comment by jeromekelleher** [comment]
Yes, well spotted. This is an easy fix: we just need to count the number of mutations over each node, and divide the distance along the branch in to this number of equal segments. The code would be here:

https://github.com/jeromekelleher/msprime/blob/master/msprime/trees.py#L294

Also, these red squares are embarrassingly ugly....

**Comment by jeromekelleher** [comment]
Fixed in #207.
