### ISSUE TITLE
No "Ne" argument in msprime.simulate()

### ISSUE THREAD

**Issue by stephenrong** [jeromekelleher/msprime#21]
From the Tutorial example, it should be possible to set a keyword argument "Ne":

> tree_sequence = msprime.simulate(sample_size=5, Ne=1000)

However, this keyword argument does not seem to be present. Using "import inspect; print inspect.getargspec(msprime.simulate)[0]", I get the following arguments:

> ['sample_size', 'num_loci', 'scaled_recombination_rate', 'scaled_mutation_rate', 'population_models', 'random_seed', 'max_memory']

**Comment by jeromekelleher** [comment]
Are you using the most recent version of msprime @stephenrong?

```python
>>> import msprime
>>> msprime.__version__
'0.3.0'
>>> tree_sequence = msprime.simulate(sample_size=5, Ne=1000) 
>>> import inspect
>>> inspect.getargspec(msprime.simulate)[0]
['sample_size', 'Ne', 'length', 'recombination_rate', 'recombination_map', 'mutation_rate', 'population_configurations', 'migration_matrix', 'demographic_events', 'random_seed', 'num_replicates']
```

You can update using pip or conda (depending on how you installed it).

Thanks for trying out the tutorial!

**Comment by stephenrong** [comment]
Ah thank you! For some reason pip installed 0.1.7 version of msprime.
