### ISSUE TITLE
Add ``samples`` argument to TreeSequence.get_pairwise_diversity()

### ISSUE THREAD

**Issue by jeromekelleher** [jeromekelleher/msprime#22]
A useful addition to the API is to add an optional argument to ``TreeSequence.get_pairwise_diversity()`` to allow calculation of pi within a given subset of the samples.

Thanks to @aylwyn for the idea.

**Comment by aylwyn** [comment]
Looking pretty good. Have tested it on 5 populations, 500 samples each, 10Mb simulation, and it takes ~0.5s per population to calculate pi. Suffice to say it's a hell of a lot quicker than my python implementation..!

**Comment by jeromekelleher** [comment]
Excellent! OK, I've merged #23 into develop, and will pop out a release tomorrow with this update. Thanks for the idea and spec @aylwyn, keep 'em coming!
