### ISSUE TITLE
Anaconda version not 0.4.0

### ISSUE THREAD

**Issue by stsmall** [jeromekelleher/msprime#221]
Hi Jerome,
Thanks for doing so much to help the community with msprime. I am using version 0.3.1 that was installed with Anaconda from the bioconda channel. I am attempting to use some of the LdCalculator functions but they were not available, by dir(msprime) in that version. When i tried to update to 0.4.0 from the bioconda channel, listed in bioconda as 0.4.0, the version still displays as 0.3.1. I tried installing 0.4.0 with pip but get a different set of errors related to wheel building, likely missing dependencies that pip is not alerting me to. Is there any chance you could verify that the bioconda channel has the current 0.4.0 version as displayed and not 0.3.1?
thank you,
scott

**Comment by ashander** [comment]
I can't reproduce this (on ubuntu 16.10, conda 4.2.13, py36)

Did you add the channels in the correct order when setting up bioconda?

Try

add channels
```
conda config --add channels defaults
conda config --add channels conda-forge
conda config --add channels bioconda
```

create new env and install msprime
```
conda create -n msp
source activate msp
conda install msprime
```

after this my `conda list` outputs

```sh
#
ca-certificates           2017.7.27.1                   0    conda-forge
certifi                   2017.7.27.1              py36_0    conda-forge
gsl                       1.16                          0    conda-forge
h5py                      2.7.0               np113py36_1    conda-forge
hdf5                      1.8.18                        0    conda-forge
libgfortran               3.0.0                         1  
mkl                       2017.0.3                      0  
msprime                   0.4.0            py36_gsl1.16_2    bioconda
ncurses                   5.9                          10    conda-forge
numpy                     1.13.1                   py36_0  
openssl                   1.0.2l                        0    conda-forge
pip                       9.0.1                    py36_0    conda-forge
pyparsing                 2.2.0                    py36_0    conda-forge
python                    3.6.2                         0    conda-forge
readline                  6.2                           0    conda-forge
setuptools                36.2.2                   py36_0    conda-forge
six                       1.10.0                   py36_1    conda-forge
sqlite                    3.13.0                        1    conda-forge
svgwrite                  1.1.6                    py36_0    bioconda
tk                        8.5.19                        2    conda-forge
wheel                     0.29.0                   py36_0    conda-forge
xz                        5.2.2                         0    conda-forge
zlib                      1.2.11                        0    conda-forge
```

**Comment by stsmall** [comment]
Hi Ashander,
Thanks for the help. I didnt have conda-forge set as default channel, the other two were a yes. That seemed to solve the problem. After following all your instructions, I still had some issues but was able to find solutions. I left details of the error message and solutions below, in the case that others have similar problems.
1) Ubuntu 16.04, Python2.7 ... Python was using system pkg HDF5, error on incompatible header from 1.18.8 and 1.18.7. Solved by "export LD_LIBRARY_PATH=~/anaconda2/lib:$LD_LIBRARY_PATH"
2) Redhat 4.4.7-1, Python2.7, GCC 4.4.7 ... ImportError: libgsl.so.0: cannot open shared object file: No such file or directory. Loaded module of GCC 4.8.2 or newer ...

Thanks for the assist!
-scott
