### ISSUE TITLE
Debug output for print(tree_sequence)

### ISSUE THREAD

**Issue by jeromekelleher** [jeromekelleher/msprime#224]
Something that's coming up over and over again for me is a the lack of a quick debug output for looking at a tree sequence. I'd like to write

```python
print(ts)
```
and get back a summary of the tables. Something like this:
```
****************
TreeSequence @abc1234
sample_size: 2
<more details>
== nodes ==
id      flags   population      time
0       1       0               0.00000000000000
1       1       0               0.00000000000000
2       0       0               1.60156352971203
== edgesets ==
id      left            right           parent  children
0       0.00000000      1.00000000      2       0,1
== migrations ==
id      left    right   node    source  dest    time
== sites ==
id      position        ancestral_state
0       0.25000000      0
== mutations ==
id      site    node    derived_state
0       0       1       1
1       0       0       1
****************
```

I think this would be very useful, and it's in the spirit of the Python ``__str__`` method as it's an informal representation of the object. 

Any thoughts/objections @petrelharp, @ashander?

**Comment by ashander** [comment]
100% in favor of having something like this built in.

The format looks good. Two thoughts:

- It might be nice to not print migrations and mutations for tree sequences
that do not have any. Perhaps that's an unneeded complication.
- Does `id` have a consistent meaning across the 5 types of data?

**Comment by petrelharp** [comment]
Yes, agree.  I've been using
```
for x in ts.dump_tables():
  print(x)
```
to do almost this.

**Comment by jeromekelleher** [comment]
Cool, thanks guys. I'll make a PR when things calm down a bit.

>  Does `id` have a consistent meaning across the 5 types of data?

I think it does -- it's just a shortcut to let you find things like nodes and sites when referred to from other tables. It seems more consistent (and less confusing) to keep ID in all the tables rather than just include it in the ones that are referred to from other tables.

**Comment by petrelharp** [comment]
I agree - and, by the way, is there a python method to get rows of tables
by id that I don't know about?

**Comment by jeromekelleher** [comment]
>I agree - and, by the way, is there a python method to get rows of tables by id that I don't know about?

No, but we could do it easily enough. Are you thinking about something like
```python
row = nodes[0]
```
where ``row`` is a namedtuple of the values (flags, population, time)? I.e., in the example above, row.flags == 1, row.population == 0.

We can do this in Python using the thin table subclasses. Easy.

**Comment by petrelharp** [comment]
Yes, exactly.  I have found myself often wanting to find the flags of the
n-th node, for instance.  Currently, I need to export tables, etcetera, to
do this.

**Comment by ashander** [comment]
>>Does id have a consistent meaning across the 5 types of data?

>I think it does -- it's just a shortcut to let you find things like nodes and sites when referred to from other tables. It seems more consistent (and less confusing) to keep ID in all the tables rather than just include it in the ones that are referred to from other tables.

So `id` means: "node" in the node table, "site" in the sites table, and row number in the other tables. The print out makes sense once you understand this but could be confusing to a user who didn't. Imagine someone thinking of these as tables in a database: joining nodes with edgesets on "id" would be nonsensical. 

This doesn't really matter if it's just a quick internal way for developers to do `str(ts)` but if you bind it to `__repr__` so that `TreeSequence` objects print out this way in the terminal, then it's going to show up for users who haven't delved into the internals. In that case it might be worth relabeling `id` to `site` in the sites table and to `node` in the nodes table.

**Comment by jeromekelleher** [comment]
> So id means: "node" in the node table, "site" in the sites table, and row number in the other tables. The print out makes sense once you understand this but could be confusing to a user who didn't. Imagine someone thinking of these as tables in a database: joining nodes with edgesets on "id" would be nonsensical.

I'm confused here: doesn't it mean row number in all the tables? The treatment is the same in all the tables, it's just that we happen to refer back to the sites and nodes table from other tables. There's nothing stopping us from having another table in the future that would refer to edgesets.

**Comment by ashander** [comment]
Your proposal seems great and that explanation makes sense.

I was initially confused and think my reaction spilled over to confuse you. Sorry!
