### ISSUE TITLE
"tracked leaves" should be "tracked samples"

### ISSUE THREAD

**Issue by petrelharp** [jeromekelleher/msprime#225]
As mentioned in #223, to change the name, keeping these as deprecated aliases:

- `tracked_leaves`
- `leaf_counts`
- `leaf_lists`

To *not* change:

- `is_leaf` and `is_internal`

but perhaps we should add a `is_sample` function.

**Comment by jeromekelleher** [comment]
> but perhaps we should add a is_sample function.

Yes, we should definitely add that I think. I would say ``is_leaf``/``is_internal`` just tell you the topological properties of a given node within a tree and ``is_sample`` tells you whether a given node is a sample.
