### ISSUE TITLE
Rename ``filter_root_mutations`` for simplify

### ISSUE THREAD

**Issue by jeromekelleher** [jeromekelleher/msprime#226]
The ``filter_root_mutations`` option for simplify is semantically awkward, and not particularly clear in what it actually does. The idea was to provide the option to remove fixed sites from the simplified tree sequence, but the terminology was different in those days. Since this hasn't been released we're free to change this.

I think that we should change the option to ``filter_invariant_sites`` and default it to True. This seem easier to follow to me. 

Any thoughts @petrelharp?

**Comment by petrelharp** [comment]
That's a much better name.  I'd also think it's fine to remove this as an
option entirely - I'm not sure what the use case would be.
