### ISSUE TITLE
Add mutations to Wright-Fisher tests

### ISSUE THREAD

**Issue by jeromekelleher** [jeromekelleher/msprime#244]
The tests in ``tests/test_wright_fisher.py`` currently only check topological properties, and mutations have been disabled in the WF simulator. Enable mutations in the simulator and write some tests.

**Comment by petrelharp** [comment]
I think that this is no longer true: for instance, [here](https://github.com/jeromekelleher/msprime/blob/master/tests/test_wright_fisher.py#L364) we check haplotypes pre- and post-simplify?

However: it is currently doing infinite sites.  We should modify this to allow recurrent mutations.
