### ISSUE TITLE
how to change the precision level of mutation position

### ISSUE THREAD

**Issue by songsy** [jeromekelleher/msprime#257]
Hi, I am interested in simulating a whole chromosome, let's say 100Mb, however, the mutation position only have 3 digit, let's say 0.029, it's impossible to map back to where the mutation is happening on the genome. I wonder if we can increase the precision level? Thank you so much!

**Comment by jeromekelleher** [comment]
I'm assuming your using the ``mspms`` command line interface rather than the Python API? If so, there is a ``--precision`` argument to control this. See the documentation via ``mspms --help`` or [here](http://msprime.readthedocs.io/en/stable/cli.html#mspms).
