### ISSUE TITLE
format="unicode" for tree.draw()

### ISSUE THREAD

**Issue by jeromekelleher** [jeromekelleher/msprime#260]
It would be super cool if we could take the existing ASCII tree drawing method and modify it so that we can also support unicode using [box drawing characters](https://en.wikipedia.org/wiki/Box-drawing_character).

It will be useful to have both ascii and unicode I think for situations where unicode won't work properly.

**Comment by ashander** [comment]
NB to a future implementer --- the ASCII method was added in #258

**Comment by jeromekelleher** [comment]
Closed in #266.
