### ISSUE TITLE
pickling tables

### ISSUE THREAD

**Issue by molpopgen** [jeromekelleher/msprime#263]
I noticed that the various table structures cannot be pickled.  An example is here, where I have added a failing unit test: https://github.com/molpopgen/msprime/commit/8ba795bd70cc34d805d70a2f6ef20c09a52dfbcd

I ran into this while attempting to use concurrent.futures to run forward simulations and return the simplified tables.  It did not work, and at least part of the reason is that the futures need to be instances of pickleable types.

There are several use cases for forward simulations where pickling would be desirable.

**Comment by jeromekelleher** [comment]
This is easy,  I think; PR open in #264.

I doubt that passing large tables around via pickling will be efficient though. It's probably better to use threads and keep everything in the same process space IMO. If the forward simulations release the GIL, this works really well in my experience.

**Comment by molpopgen** [comment]
Yeah, it will be a bit of a bottleneck, but the use cases I'm thinking of will be ok with that:

1. Saving time points to a pickled archive for later analysis (or even re-starting a simulation).  If I can pickle a (pop, tables) tuple, I can sample time points to files.

2. One reason to use concurrent.futures rather than threads is that the master process can archive all output to a single file.  This is useful as HPC systems with "fancy" file systems hate having lots of files around.  We do this a lot, using pickling to send many Gb of simulated populations b/w processes.  It is fast enough that we don't worry about it.

3. Executing work flows across compute nodes via MPI also requires pickling.

**Comment by jeromekelleher** [comment]
Sounds good; will merge as soon as Travis build completes (will be a while).

OT: thinking of turning off OSX builds entirely. Hardly seems worth the hassle.

**Comment by molpopgen** [comment]
> OT: thinking of turning off OSX builds entirely. Hardly seems worth the hassle.

Yep...
