### ISSUE TITLE
Bad edge interval on some simulations

### ISSUE THREAD

**Issue by rwaples** [jeromekelleher/msprime#278]
I'm trying to simulate something like multiple chromosomes (via a recombination map) along with a past bottleneck and I'm getting an error: "LibraryError: Bad edge interval where right <= left"

msprime version: '0.4.1.dev696+g299ddc9'

See example code below.  The error is produced most, but not all of the time, and the rate seems sensitive to the Ne and sample_size parameters 

```python
import msprime

rm = msprime.RecombinationMap(
    [0.0, 50000000.0, 50000001.0, 100000000.0], 
    [1e-08, 0.5, 1e-08, 0.0])

de = [ msprime.PopulationParametersChange(time=100, initial_size=2000)]

msprime.simulate(Ne = 400,
    mutation_rate=1e-8,
    recombination_map = rm,
    sample_size = 400,
    demographic_events = de,
                    )
```

**Comment by jeromekelleher** [comment]
Thanks for the excellent bug report @rwaples, I've just reproduced this problem. I'll update when I figure it out.

**Comment by jeromekelleher** [comment]
This seems like an odd parameter regime @rwaples --- do you really want to specify a very narrow region (100 millionth of the sequence length) with an enormously (~ 7 orders of magnitude) elevated recombination rate? I think there's  numerical problem arising from trying to squeeze so much of the recombination into such a tiny space of the output sequence. I can dig into it a bit more, but I just wanted to check that this is a real simulation regime first!

**Comment by jeromekelleher** [comment]
I think we can solve this problem easily enough:
```python
num_loci = 10**8 + 1
mid = num_loci // 2

rm = msprime.RecombinationMap(
        [0.0, mid, mid + 1, num_loci],
        [1e-08, 0.5, 1e-08, 0.0],
        num_loci=num_loci)
```
Msprime really works in a discrete loci model (by default 2**32 - 1), and then maps into the continuous physical space. By having a smaller number of loci, it should be much less likely that we have a collision where two points in genetic space map to precisely the same output coordinate in physical space. Seems to work OK for me anyway.

Does this solve your problem?

**Comment by rwaples** [comment]
Thanks for the quick reply!
I agree it is a bit of a weird parameter regime, certainly a bit of a hack.  You have the basic idea, I want to generate LD across chromosomes, and also LD caused by the bottleneck.  But in this case my intuition is that the cross-chromosome correlation specifically derived from the bottleneck would be gone.

I hadn't seen the "num_loci" parameter, I does solve my issue.

**Comment by jeromekelleher** [comment]
Excellent, happy to help!
