### ISSUE TITLE
Docs: update requirements

### ISSUE THREAD

**Issue by petrelharp** [jeromekelleher/msprime#291]
Making a list of requirements, and notable non-requirements here. As discussed in #288 :

1. Mutation IDs must be larger than their parent mutation IDs.

... or, should this have the caveat that "any parent mutation IDs *on the same branch*"?

- may have more than one mutation on the same branch
- derived state may be equal to ancestral state
- root may have mutations
- there may be a site with no mutations

**Comment by jeromekelleher** [comment]
> or, should this have the caveat that "any parent mutation IDs on the same branch"?

I think this is a useful requirement in general, because it captures the idea that we apply the effects of the older mutations first. Otherwise, when we apply the mutations in haplotypes/variants we have to sort them root-to-leaf somehow. I guess we could add a 'time' field to mutations and explicitly sort on them, like we do for nodes.

> derived state may be equal to ancestral state

The ancestral state of the site, or the inherited state before the mutation is applied? We do actually check to see if the new state isn't equal to the old state at the moment, so I'm not sure about this one.

**Comment by petrelharp** [comment]
I'm fine with that requirement; just trying to avoid extra complications.  I can also imagine someone needing to add mutations backwards in time, but I'm only imagining it. =)

>  Otherwise, when we apply the mutations in haplotypes/variants we have to sort them root-to-leaf somehow.

Isn't this the sort of thing the `parent` column will make easy?

> I guess we could add a 'time' field to mutations and explicitly sort on them, like we do for nodes.

`time` would tell us more about the history, but it's a whole new column; I think if people want to know that they can record it separately; it's not worth the extra cost in general.

> The ancestral state of the site, or the inherited state before the mutation is applied? We do actually check to see if the new state isn't equal to the old state at the moment, so I'm not sure about this one.

I meant the old state.  Is that assumption used anywhere?  Dropping it makes adding mutations substantially easier.

**Comment by petrelharp** [comment]
Oh, I see in #288 that you've already got a check for this in.  I'm inclined to leave it as-is.

**Comment by jeromekelleher** [comment]
> Isn't this the sort of thing the parent column will make easy?

I haven't looked at the haplotypes/variants code to see if we can use 'parent' there. It would be nice if we could, or at least use them to throw an error when something strange happens.

> I meant the old state. Is that assumption used anywhere? Dropping it makes adding mutations substantially easier.

It seems like a good error check to me. Why would you want to put on a mutation that had the same state as something that it inherits? This seems like something you'd only do if you make a mistake to me (and it's generally very helpful when a program tells you you've  made a mistake)

**Comment by petrelharp** [comment]
> Why would you want to put on a mutation that had the same state as something that it inherits? This seems like something you'd only do if you make a mistake to me (and it's generally very helpful when a program tells you you've made a mistake)

Putting down a mutation that differs from the parent requires knowing what the parent is.  If you're doing parent-independent mutation, then not having to figure out what the parental type is makes adding mutations dead easy.  But, real mutations are not parent-independent, so maybe we shouldn't encourage that.

**Comment by jeromekelleher** [comment]
> Putting down a mutation that differs from the parent requires knowing what the parent is. If you're doing parent-independent mutation, then not having to figure out what the parental type is makes adding mutations dead easy. But, real mutations are not parent-independent, so maybe we shouldn't encourage that.

It's still pretty easy though, right? There is an argument for letting go of this restriction all right, and it would make life a bit easier in simplify because we wouldn't have to get rid of mutations that are the same state as the ancestral state. I just feels wrong to me though!

**Comment by petrelharp** [comment]
Yeah, it's still pretty easy.  I think the cost/benefits of removing this restriction are:
   less checking for wierdly mixed-up input / but more flexible.
Neither of these things seems at this point big considerations, so I guess I'd vote for the path of least resistance.  Which is keeping this requirement?

**Comment by jeromekelleher** [comment]
> Yeah, it's still pretty easy. I think the cost/benefits of removing this restriction are:
less checking for wierdly mixed-up input / but more flexible. Neither of these things seems at this point big considerations, so I guess I'd vote for the path of least resistance. Which is keeping this requirement?

I would vote for the path of least resistance too, which is to keep things as they are (i.e., the parent is defined before children  requirement stays).

**Comment by petrelharp** [comment]
Roger on keeping the requirements that mutations in order consistent with the tree-defined partial order.  It makes the `compute_parents` algorithm pretty nice.

Also, keeping derived state != derived state of parent mutation, I guess - removing this later shouldn't actually break anything.

**Comment by petrelharp** [comment]
OK; I think that the `compute_parents` algorithm is good.  It only takes a tree sequence now, which I think is fine.  Also I don't see it being important to move this to C, contrary to what I started out saying?  Except that to use it for checking, or as an optional argument to `load_tables`, perhaps we do?
