### ISSUE TITLE
Docs: include example of subsampling  sites in a tree sequence

### ISSUE THREAD

**Issue by jeromekelleher** [jeromekelleher/msprime#292]
We should give a simple example of how to edit tree sequences. For example, randomly subsampling the sites output by a simulation would be a good example, as lots of people do this. Possibly this should go in the tutorial.

**Comment by ashander** [comment]
In the tutorial makes sense. 

As #229 will not be implemented for 0.5.0 this would be using the workflow mentioned herehttps://github.com/ashander/msprime/blame/8d659b6c407a04a63b7d2e261a8a911a8346afb2/docs/file-format.rst#L365-L369
