### ISSUE TITLE
Error for multiple population events at same time

### ISSUE THREAD

**Issue by terhorst** [jeromekelleher/msprime#3]
The following runs fine using ms or scrm but results in an error with msprime: ```<simulator> 5 1 -t .001 -eN 0.0 10.0 -eG 0.0 -.01 -eN 1.0 1.0```. The error given by msprime is "_msprime.InputError: Bad parameter value provided". I believe the problem is at lib/msprime.c:194. The "<=" should be a strict "<".

**Comment by jeromekelleher** [comment]
Thanks very much for the bug report and analysis @terhorst!

I'm afraid I don't quite see how this is a legal input  though --- which model are we saying covers the time interval 0.0 - 1.0 here? I guess ms probably uses the "-eG 0.0 -.01" model and ignores the "-eN 0.0 10.0" one, but why would we want to allow the user specify population models that are ignored? Is there a use-case where this behaviour is important? 

In either case though msprime does need much better error handling and reporting for population model specification.

**Comment by paulstaab** [comment]
I think it is valid input for ms (it definitely is for scrm). The population starts at size 10 N0, and is then slowly expanding from that backwards-in-time (i.e. decline forward in time).

**Comment by jeromekelleher** [comment]
Ah OK, thanks @paulstaab. Is this documented behaviour in ms? It still seems a bit confusing to me through --- N0 being different to N at time 0 is a weird idea! I guess this makes more sense when we look at multiple populations though, where we do need to do this sort of thing. Is this special case at t=0, or do we need to support multiple instantaneous population size changes at any point in time?

**Comment by paulstaab** [comment]
Yes, the model doesn't make a lot of sense, but I think @terhorst created a simplified example. Ms' manual does a horrible job of exampling this, but I I verified that it produces identical distributions to scrm which acts this way. In ms, the instantaneous sizes changes (-en) are pretty independent from the population growth rates (-eg) , and both can be changed at the same time.

**Comment by jeromekelleher** [comment]
OK, makes sense @paulstaab. @terhorst, what's your take here --- what's your motivation for having multiple events occuring at the same time? I'm happy to change msprime's behaviour here, I'd just like to understand the thinking behind this a bit better.

**Comment by terhorst** [comment]
The use cases I have in mind are mixed piecewise-constant and
piecewise-exponential models. These are commonly used for fitting
demographic models to data. I am using msprime and/or scrm to test just
such a thing on simulated data. Thanks,

Jonathan

**Comment by jeromekelleher** [comment]
OK, thanks @terhorst, I'll fix this and make sure it's doing something sensible. I'd imagine that I'll fix it by detecting equal time values on the command line for mspms, and replace the time value for the exponential with t + epsilon. If you want to get this running now, you could just write 
```
mspms 5 1 -t .001 -eN 0.0 10.0 -eG 1e-100 -.01 -eN 1.0 1.0
```
This seems logically a bit more sensible in any case --- we have a very brief instant of time under which the constant model holds, after which the exponential model follows until t=1.0.

There's a balance here for me between making mspms compatible with ms, but not propagating ms's weird UI through to msprime's Python API, which I would like to be simple and logical.

**Comment by jeromekelleher** [comment]
This is fixed in version 0.1.8 --- we should have full compatibility with ms semantics in mspms now for this sort of input. Thanks again for the bug report!
