### ISSUE TITLE
Seeding a MutationGenerator

### ISSUE THREAD

**Issue by molpopgen** [jeromekelleher/msprime#303]
Is it possible to fix the seed for this object? I tried to pass `random_seed` as a `kwarg`, but it was rejected. 

I guess the issue really is that the valid `kwargs` are not documented

**Comment by jeromekelleher** [comment]
The MutationGenerator takes a RandomGenerator as a parameter, not a seed. This is done here:

https://github.com/jeromekelleher/msprime/blob/master/_msprimemodule.c#L2714

So, basically you just need to create a RandomGenerator instance with the seed you want.

**Comment by molpopgen** [comment]
Thanks.  Turns out that I was doing it right and that my reproducibility issue was not seeding numpy properly elsewhere.

Understood re: the current dox.  Is the API likely to change in the 0.4.1 release?

**Comment by jeromekelleher** [comment]
> Understood re: the current dox. Is the API likely to change in the 0.4.1 release?

No, I don't think it will change for this release. I want to make a more general framework for generating mutations (i.e., allow back mutations, Jukes-Cantor, etc) at some point, so I'm not documenting this stuff until that's been at least thought through properly. I won't change the current API without pinging you first though.
