### ISSUE TITLE
`is_sample` or `flags`?

### ISSUE THREAD

**Issue by petrelharp** [jeromekelleher/msprime#314]
A minor but sufficiently confusing issue that I think it's worth fixing up: for a NodeTable, `dump_text` and `load_text` uses the `is_sample` column; whereas `print` gives a `flags` column, so you can't paste the output from print directly into a file and `load_text` it (you must change the header).

Solutions:

1. change `print` to output `is_sample` instead of `flags`
2. change `dump_text` and `load_text` to use `flags` instead of `is_sample`
3. allow `load_text` to take either, or possibly *both* columns, as [implemented here](https://github.com/petrelharp/msprime/tree/load_flags)

I think the best option may be (1); since no other flags are currently being used. But, if you think it's likely you'll be adding other flags, then (3); what's lacking to merge that implementation is a test or two.

**Comment by jeromekelleher** [comment]
I think you're right and (1) is the best option. I can't think of any other flags we might use at the moment, so there's no point in confusing users with this. Having a bitwise flags column as part of the text interface is probably a bad idea anyway.

**Comment by petrelharp** [comment]
Done in #318
