### ISSUE TITLE
Releasing the GIL for various tables API operations

### ISSUE THREAD

**Issue by molpopgen** [jeromekelleher/msprime#315]
Opening this issue as a result of our recent emails, so that we have a place to track it.

Some or all of the current set/append/sort/simplify functionality does not release the GIL.  It would be helpful to do so.

**Comment by jeromekelleher** [comment]
On a scale of 0-10 how critical path is this for you? I can do this, but it's subtle because the tables realloc memory dynamically and guaranteeing pointers are always valid isn't trivial.

**Comment by molpopgen** [comment]
It's pretty up there--in the 8+.  The reason is the integration w/forward sims.  Time-series analysis of the population during simulation is becoming more common, and the "analyzer" is often a Python callable. A lot of GIL contention would be minimized if as much as the longer-running C side of msprime weren't holding onto it.

**Comment by jeromekelleher** [comment]
OK cool. Will push this up the stack so and take a look in the next few days. I'll ping you when there's something to try.

**Comment by jeromekelleher** [comment]
Closed in #320
