### ISSUE TITLE
historical samples in a multi-populations model

### ISSUE THREAD

**Issue by hsiehph** [jeromekelleher/msprime#317]
Hello,

I am interested in simulating a multi-populations model, in which one of the populations was sampled 500 generations ago. For example, a model of three populations (indices 0, 1, and 2), where pop0 is the one with historical samples. The haploid sample sizes are 4, 100, and 200 for pop0, pop1, and pop2, respectively. 

What is the easiest way to set up the arguments for msprime.simulate()? The following is what I have so far. I am not sure if I can use both population_configurations and samples in msprime.simulate() and if I have to specify samples in pop1 and pop2 that are sampled at time = 0. 
It seems a bit tedious, if it is indeed required for msprime, to construct a very long list for these modern day samples for pop1 and pop2.

Any comment and suggestion would be great.

Thanks,
Benson

#############
pop_configs = [ msprime.PopulationConfiguration(sample_size=4, initial_size=pop0_size), msprime.PopulationConfiguration(sample_size=100, initial_size=pop1_size), msprime.PopulationConfiguration(sample_size=200, initial_size=pop2_size)] 

samples = [ msprime.Sample(population=0, time=500), msprime.Sample(population=0, time=500, msprime.Sample(population=0, time=500), msprime.Sample(population=0, time=500)]
#############

**Comment by jeromekelleher** [comment]
I'm afraid you can't mix sample_size in the population configurations and historical samples. However, this is pretty easy to workaround:

```python
pop_configs = [ 
    msprime.PopulationConfiguration(initial_size=pop0_size), 
    msprime.PopulationConfiguration(initial_size=pop1_size),  
    msprime.PopulationConfiguration(initial_size=pop2_size)]

samples = (
    [msprime.Sample(population=0, time=500) for _ in range(4)] +
    [msprime.Sample(population=1, time=0) for _ in range(100)] + 
    [msprime.Sample(population=2, time=0) for _ in range(200)])
```
I haven't tested this but it should do the trick.

**Comment by hsiehph** [comment]
Thanks for the tip!
