### ISSUE TITLE
Allow degenerate mutations?

### ISSUE THREAD

**Issue by jeromekelleher** [jeromekelleher/msprime#329]
As discussed in #328, we currently detect and raise an error when mutations are specified that result in no change of state (e.g., a mutation which says the derived state is A, but the ancestral state is already A).

I think this will usually indicate an error, so it's a handy error checking feature for users. I think @petrelharp  sees it differently though, and these mutations will occur and it's an unnecessary pain to weed them out.

Any other thoughts? @molpopgen, what do you think?

I'm happy to just remove this check if we agree that degenerate mutations are a real thing.

**Comment by molpopgen** [comment]
I agree with @jeromekelleher--I think allowing this compromises correctness and creates challenges for sticking to the "fail as early as possible" idiom.

Recurrently mutating to the same position over and over is a sign of a poorly-implemented mutation model, IMO.  It is trivial to prevent these situations via the use of hashing tables such as `dict` or what I do [here](https://github.com/molpopgen/fwdpp/blob/master/fwdpp/extensions/regions.hpp#L99), where the `lookup_table_t` must be a duck-type for the API of [`std::unordered_set<double>`](http://en.cppreference.com/w/cpp/container/unordered_set).

**Comment by petrelharp** [comment]
I defer to you all, then!

In my defense, I was going with the "if it's not wrong, don't fail" point of view to make things easier on ourselves.

If someone needs to input data with such mutations, it'd be straightforward to write a script to remove them.

**Comment by jeromekelleher** [comment]
OK, sounds like we have agreement then. We keep things as they are -- but, are open to the idea of making this configurable behaviour in the future if a use-case shows up.
