### ISSUE TITLE
Separators for text formats

### ISSUE THREAD

**Issue by jeromekelleher** [jeromekelleher/msprime#337]
The issue of what separators we allow in the text file format popped up in #333, which merged a method that allows us to reliably round-trip data through the text file format and also support relaxed whitespace delimited inputs. Both of these are hard requirements (we need relaxed whitespace because these are the current semantics, and we don't want to gratuitously break people's code).

Under the current code, we have

```python
ts = msprime.load_text(nodes_file, edges_file, sites_file, mutations_file)
```

By default, this will read general whitespace delimited files, but will break if there are (a) indels, or (b) the metadata column is empty and is not the last column in the file. To reliably read arbitrary input data it must be strictly tab-delimited and we must write

```python
ts = msprime.load_text(nodes_file, edges_file, sites_file, mutations_file, sep="\t")
```

Here ``sep`` is interpreted exactly as it is in [str.split](
https://docs.python.org/3.5/library/stdtypes.html#str.split). In principle, this allows us to use other separators for the input file, but there are a number of gotchas: we can't use commas (for reasons it's not worth getting into), and we also have to beware of using characters in base64. 

This seems like more trouble than its worth to me: we'll need to carefully enumerate the separators that we do allow, and make sure that what the user provides is one of them. But, what's the point? What does the user actually gain by having this freedom to choose from a number of different delimiters? It just seems like an unnecessary complication to me. For example, if we ever decided that we needed to make text input faster, then it'd be quite complicated to duplicate this in C.

For these reasons, I would prefer to change this to
```python
ts = msprime.load_text(nodes_file, edges_file, sites_file, mutations_file, strict=True)
```
Now we only have two choices of delimiter: either strict tab delimited (strict=True) or relaxed whitespace (strict=False). To ensure that we can reliably round-trip data by default, strict will default to True. To read in existing whitespace delimited files, we will need to add ``strict=False`` to all calls.

I think it's important we get this right, so I'd really appreciate any input you may have on this @ashander, @petrelharp and @molpopgen!

**Comment by petrelharp** [comment]
I think this is a good proposal!

**Comment by molpopgen** [comment]
I agree--keep it simple.

**Comment by jeromekelleher** [comment]
Cool --- I'll code this up so.

**Comment by ashander** [comment]
+1 from me too
