### ISSUE TITLE
Ne parameter query

### ISSUE THREAD

**Issue by deponentverb** [jeromekelleher/msprime#347]
Hello.

I am having some trouble understanding how to appropriately use the Ne parameter in my simulations. The API defines Ne as "The effective (diploid) population size for the reference population." If I am simulating a model with multiple demes which one would constitute the "reference population?" Should Ne be the effective pop size of the "trunk" when all the demes have coalesced? 

Thanks.

**Comment by jeromekelleher** [comment]
Hi @deponentverb. This is a good question, but one that would be better suited to the msprime users [mailing list](https://groups.google.com/forum/#!forum/msprime-users). Would you mind reposting the question there please? (Hopefully Google will pick up these questions and answers over time on the mailing list, so people can find the answers by searching.)
