### ISSUE TITLE
0.5.0 release plan

### ISSUE THREAD

**Issue by jeromekelleher** [jeromekelleher/msprime#349]
After #346 is merged, I think we've covered most of the outstanding documentation requirements for the tables API. I think it's time to release 0.5.0b1.

- 0.5.0b1 is the first beta, and with documentation for all the tables API. Use this to (a) allow people play with tables API; and (b) get feedback from existing users on whether we've broken their code.
- 0.5.0b2 should include the remaining release items for the 0.5.0 milestone, and should follow in a week or two.
- 0.5.0 should follow quickly after that.

This is all assuming that things go smoothly, of course!

Pinging @petrelharp, @molpopgen and @ashander to keep you in the loop.

**Comment by petrelharp** [comment]
yay!!

**Comment by jeromekelleher** [comment]
> awesome. let me know if there's any easy-to-delegate contribs to docs or fixes

It would be super helpful if you take a look at the "Processing Results" section of the docs now at see if you can spot any issues. I think I have most things sorted out now, but another pair of eyes on things like the ``variants`` iterator would help a lot.

http://msprime.readthedocs.io/en/latest/api.html#processing-results

I'll probably roll another beta tomorrow so we can try out these API updates. After that it's a matter of cleaning up the last few niggling issues, and writing up the release notes. It will probably need a third beta all right though.
