### ISSUE TITLE
Sample historical sample with demographic history 

### ISSUE THREAD

**Issue by xinyli** [jeromekelleher/msprime#366]
Hi, I am generating an admixed population with proportion p using the below demographic model: 
demographic_events = [
                                                                                                                       
        msprime.MassMigration(
            time=T_ADM, source=3, destination=1, proportion=p),
        msprime.MigrationRateChange(time=T_ADM, rate=0),
        msprime.MigrationRateChange(time=T_ADM, rate=m_EU_EAS, matrix_index=(1,2)),
        msprime.MigrationRateChange(time=T_ADM, rate=m_EU_EAS, matrix_index=(2,1)),

        msprime.MassMigration(
            time=T_PEL, source=3, destination=2, proportion=1.0),

        msprime.MigrationRateChange(time=T_PEL, rate=m_AF_EU, matrix_index=(0,1)),
        msprime.MigrationRateChange(time=T_PEL, rate=m_AF_EU, matrix_index=(1,0)),

        msprime.MigrationRateChange(time=T_PEL, rate=m_AF_EAS, matrix_index=(0,2)),
        msprime.MigrationRateChange(time=T_PEL, rate=m_AF_EAS, matrix_index=(2,0)),

        # CEU and EAS merge into B with rate changes at T_EU_NAT                                                                                                       
        msprime.MassMigration(
            time=T_EU_EAS, source=2, destination=1, proportion=1.0),
        msprime.MigrationRateChange(time=T_EU_EAS, rate=0),
        msprime.MigrationRateChange(
           time=T_EU_EAS, rate=m_AF_B, matrix_index=(0, 1)),
        msprime.MigrationRateChange(
            time=T_EU_EAS, rate=m_AF_B, matrix_index=(1, 0)),
        msprime.PopulationParametersChange(
           time=T_EU_EAS, initial_size=N_B, growth_rate=0, population_id=1),

        # Population B merges into YRI at T_B                                                                                                                          
        msprime.MassMigration(
            time=T_B, source=1, destination=0, proportion=1.0),

        # Size changes to N_A at T_AF                                                                                                                                  
        msprime.PopulationParametersChange(
           time=T_AF, initial_size=N_A, population_id=0)
    ]

My simulated population is an admixture between a drifted population from EAS and EU. Can I sample this drifted population from EAS (before admixture event) ? I know there is a function with msprime.sample. However, it seems like the sample option can not be used with the population_configuration together.

Thank you.

**Comment by jeromekelleher** [comment]
When working with ancestral samples you do need to specify all the samples manually using the ``samples`` argument, and you cannot use the ``sample_size`` argument to the ``PopulationConfiguration`` objects.  But the timing is arbitrary and can be interleaved with any number of demographic events. Here's an example from msprime's test suite:
```python
        t1 = 1.5
        t2 = 10.5
        t3 = 50.5
        ts = msprime.simulate(
            Ne=1/4,
            samples=[
                msprime.Sample(0, 0),
                msprime.Sample(1, t1),
                msprime.Sample(2, t2),
                msprime.Sample(3, t3)],
            population_configurations=[
                msprime.PopulationConfiguration(),
                msprime.PopulationConfiguration(),
                msprime.PopulationConfiguration(),
                msprime.PopulationConfiguration()],
            demographic_events=[
                msprime.MassMigration(time=t1, source=0, destination=1),
                msprime.MassMigration(time=t2, source=1, destination=2),
                msprime.MassMigration(time=t3, source=2, destination=3)])
```

Hope this helps.

**Comment by jeromekelleher** [comment]
Assuming this is OK, so closing.
