### ISSUE TITLE
migration example question

### ISSUE THREAD

**Issue by jhmarcus** [jeromekelleher/msprime#399]
Hey @jeromekelleher,

Really enjoying using `msprime`! Its very useful software. I have a quick question about specifying the migration matrix. In the [population structure](https://msprime.readthedocs.io/en/latest/tutorial.html#population-structure) example in the docs the migration matrix has zeros on the diagonal ...

```
migration_matrix = [[0, m, m], [m, 0, m], [m, m, 0]]
```

Is the input supposed to be a backwards migration matrix, i.e. a stochastic matrix whose rows sum to 1 and m_ij is interpreted (akin to ms)  as "the fraction of subpopulation i which is made up of migrants from subpopulation j". Thanks!

**Comment by jeromekelleher** [comment]
Hi @jhmarcus; thanks, great to hear msprime is working well for you!

I've been working on a new tutorial as a book chapter, which I hope will answer your question. See the "Population structure" section in this [notebook](https://github.com/jeromekelleher/spg-chapter/blob/master/jupyter/simulations.ipynb)

(It would be good to get your feedback on the whole chapter, if you woulnd't mind; if you send me an email I'll send on the PDF. I'd really like to get these sorts of questions answered for good!)

**Comment by jhmarcus** [comment]
Great! Thanks @jeromekelleher. Would be happy to give feedback. I'll send you an email.
