### ISSUE TITLE
Anaconda and gsl

### ISSUE THREAD

**Issue by stsmall** [jeromekelleher/msprime#4]
Hi,
I am attempting to install msprime on both Mac osX el Capitan and RedHat Linux-64.
On osX:
I followed the instructions and installed gsl and hdf5 using brew, but also using "conda install" for gsl and hdf5: "conda install -c https://conda.anaconda.org/asmeurer gsl" and "conda install hdf5"
I then tried: "conda install --channel https://conda.anaconda.org/bioconda msprime"
but received the message: "No packages found in current osx-64 channels matching: msprime"
This made sence since I did not see a conda package for osX using "anaconda -search -t conda msprime". When I treid to install using pip, I ran into a mess of issues since anaconda is my main python distribution and brew and anaconda are not playing well together. I would like to continue using python through anaconda since it has pandas, scipy,numpy, etc... already integrated.

On Linux-64:
gsl is already installed plus I installed using  "conda install -c https://conda.anaconda.org/asmeurer gsl" and "conda install hdf5" When I run "conda install --channel https://conda.anaconda.org/bioconda msprime" I now get the message: "Error: Could not find some dependencies for msprime: gsl"
Is there a way to link the gsl to msprime install? what should I do next?

thanks!

**Comment by stsmall** [comment]
osX update: I determined that the pip package being used was not in anaconda. When I made certain to use that pip, the program installs correctly. 

Still having an issue with Linux-64.

**Comment by jeromekelleher** [comment]
Thanks for trying out msprime @stsmall!

On linux-x64 it should be simple. The Bioconda recipe should resolve all the dependencies for you, once you set up the channels it depends on. Following the [Bioconda docs](https://bioconda.github.io/) you set
```
$ conda config --add channels r
$ conda config --add channels bioconda
```

Then, you should be able to run 
```
$ conda install msprime
```
and the dependencies will be automatically pulled in. You might want to remove the version of GSL you've already installed though.

For OSX, I'm afraid it's not so simple. I hope to get a Bioconda package built for OSX soon, but I've hit some obscure issue which I need to resolve. (See the PR [here](https://github.com/bioconda/bioconda-recipes/pull/671)). I'll try and fix it soon and update here.

**Comment by stsmall** [comment]
Hi Jerome,
Thank you! That fixed the issue.

**Comment by jeromekelleher** [comment]
msprime is now available on Linux and OSX on bioconda. Closing this issue.
