### ISSUE TITLE
Upgrade circle CI to 2.0

### ISSUE THREAD

**Issue by jeromekelleher** [jeromekelleher/msprime#417]
Circle CI will be removing support for 1.0 in August, so should update the circle CI tests.

@ashander, I seems to remember you've used circle 2.0 before. Any thoughts?

**Comment by ashander** [comment]
Yes it's been working ok [for ftprime](https://github.com/ashander/ftprime/blob/master/.circleci/config.yml). I mentioned in another issue I was motivated by using conda on top of a small docker image.

To migrate the current setup may get a little annoying with figuring out some docker stuff. But worth a try so I put in a draft PR based on my yml. Not sure if it'll work without your doing something on the circleci side ...

**Comment by jeromekelleher** [comment]
Closed in #420.
