### ISSUE TITLE
Add msprime to GSR

### ISSUE THREAD

**Issue by paulstaab** [jeromekelleher/msprime#5]
Hi @jeromekelleher ,

have you thought about adding msprime to the [Genetic Simulation Resources (GSR)](http://popmodels.cancercontrol.cancer.gov/gsr/)? I don't know how wide the site is used, but I really like the idea.

Best,
Paul

**Comment by jeromekelleher** [comment]
Great idea @paulstaab, thanks for pointing this out. I didn't know about it, and it looks like a great resource. I'll add msprime to the list if/when the paper is published so there's no confusion with references.

**Comment by jeromekelleher** [comment]
A request to add msprime to the GSR has been sent.

**Comment by jeromekelleher** [comment]
Msprime is now registered with GSR: http://popmodels.cancercontrol.cancer.gov/gsr/packages/msprime/
