### ISSUE TITLE
Make API more Pythonic by removing lots of 'get_'s

### ISSUE THREAD

**Issue by jeromekelleher** [jeromekelleher/msprime#64]
Several aspects of the API are a little non-Pythonic. Mainly, this involves using methods like `obj.get_x()` rather than `obj.x`. 

For example, we should change:
- SparseTree.get_root() -> SparseTree.root
- SparseTree.get_index() -> SparseTree.index
- SparseTree.get_interval() -> SparseTree.interval
- TreeSequence.get_sample_size() -> TreeSequence.sample_size
- TreeSequence.get_num_mutations() -> TreeSequence.num_mutations

Also, we should change things like
- SparseTree.get_branch_length(u) -> SparseTree.branch_length(u)
- SparseTree.get_mrca(u, v) -> SparseTree.mrca(u, v)

Existing methods should all be marked as deprecated, removed from the documentation, and (eventually) removed entirely.

**Comment by ashander** [comment]
I could help out as I familiarize myself with the API. I opened a PR with a list of candidate functions

**Comment by ashander** [comment]
A question:  should the above be eg `SparseTree.root()`? (you don't intend to change them from instance methods, right?)

**Comment by jeromekelleher** [comment]
This is great @ashander, thanks! I think we do want to make them properties; I'll go into more detail on how your PR.

**Comment by shajoezhu** [comment]
sometimes I think github should have a 'like' buttom for things like this

**Comment by jeromekelleher** [comment]
Finally finished this up in #384.
