### ISSUE TITLE
Stricter input checking needed

### ISSUE THREAD

**Issue by jeromekelleher** [jeromekelleher/msprime#86]
PR #85 relaxed the input restrictions to allow a much broader class of tree sequence to be read in. However, testing over these wider cases is very limited. Much better testing and classification of what can be supported must be done before the code can be released.

**Comment by ashander** [comment]
Is the goal to 1) add checks on what is input via the high level api or 2) test robustness of core methods to what's currently input-able?

**Comment by jeromekelleher** [comment]
Both (1) and (2) I think @ashander. The old input checking was quite strict, which meant that we could rely on quite a few assumptions. This made it relatively easy to ensure the low-level C code was safe (which is my primary concern). So, I think the goal is to (a) try and figure out what we can can accept, and write checks to ensure this; and (b) get some decent test coverage over these classes of input.

**Comment by jeromekelleher** [comment]
This is covered thoroughly now. Closing.
