### ISSUE TITLE
provide `make clean` target

### ISSUE THREAD

**Issue by hyanwong** [jeromekelleher/msprime#89]
I *think* all this needs is the following rule in the top level Makefile

```
clean:
        rm -fR build
        rm *.o *.so
```

**Comment by jeromekelleher** [comment]
Yep, this will do the trick. Feel free to open a PR!

**Comment by hyanwong** [comment]
For something this trivial I thought you might just stick it in yourself :)

**Comment by ashander** [comment]
Seems related to #92 but there is already a target in `lib/Makefile`. Just need to add part of what's above to it
