### ISSUE TITLE
Document development environment and process

### ISSUE THREAD

**Issue by ashander** [jeromekelleher/msprime#92]
Some libraries needed to compile the c extension separately (by running `make` in lib) aren't directly documented (e.g. `libcunit1-dev`, `libconfig-dev`)

Also, it would be helpful to provide any tips on what's necessary to debug /recompile the c extension when making changes. (Or a link to common-knowledge resources on this ;)

**Comment by jeromekelleher** [comment]
Yes, this is absolutely needed @ashander. I'll do it on the next documentation update. In the mean time, feel free to shoot questions at me.
