### ISSUE TITLE
msprime.load_records() function needed

### ISSUE THREAD

**Issue by jeromekelleher** [jeromekelleher/msprime#94]
The existing ``msprime.load_txt()`` function loads a tree sequence from a set of text files. We also want to have an equivalent function that loads a tree sequence from lists of records, i.e.
```python
def load_records(coalescence_records, mutations=[], samples=None):
    # Load the tree sequence using low level methods.
```

We should change ``TreeSequence.load_records()`` static method to ``TreeSequence.parse_records()`` which returns a list of ``CoalescenceRecord`` objects. This should provide a more efficient and convenient approach for importing coalescence records than exporting to text and parsing.

Any thoughts @petrelharp, @ashander, @hyanwong?

**Comment by hyanwong** [comment]
We presumably want to pass in a list for each record. For my purposes I would like to have a python function that imports records incrementally into a tree structure. So I can call `ts.new_record(left, right, parent, children, ...)`, then when I'm done, call a function to finalise the tree structure.

**Comment by jeromekelleher** [comment]
At the moment, I've been using code like this to create records:
```python
records = [
    msprime.CoalescenceRecord(left=0, right=1, children=(0, 1), parent=2, time=2, population=0)
]
# Then, import with
ts = msprime.load_records(records)
```
So, we just create lists of the ``CoalescenceRecord`` objects and pass them in to ``load_records``. Does this seem OK?

Incrementally updating a tree sequence with new records seems a bit tricky semantically. See a discussion of why we want to make tree sequences immutable in #59.

**Comment by hyanwong** [comment]
Sure, that's OK as long as we don't mind using the intermediate storage.

**Comment by jeromekelleher** [comment]
Yeah it'll be fine. We can always make another interface based on numpy arrays later when/if we're dealing with really huge inputs.

**Comment by ashander** [comment]
@jeromekelleher  we're using the same type of code so this seems perfect

**Comment by petrelharp** [comment]
I agree.  I've been doing
```
ts = _msprime.load_records(records)
```

**Comment by hyanwong** [comment]
So does that mean the function already exists, but is hidden/undocumented?

**Comment by jeromekelleher** [comment]
The exact function doesn't exist, but it is an easy combination of existing (hidden) functions. Something like
```python
ll_ts = _msprime.TreeSequence()
ll_ts.load_records(records)
ll_ts.set_mutations(mutations)
ts = msprime.TreeSequence(ll_ts)
```

People really shouldn't use the low-level APIs though, as these can and will change arbitrarily in the future!

**Comment by jeromekelleher** [comment]
This has been superseded by the tables API.
